### ISSUE TITLE
Should the guidelines point to review teams

### ISSUE THREAD

**Issue by rjsparks** [ietf/id-guidelines#1]
Should there be a pointer to YANG doctors or the IoT review team?
Should there be a pointer to all review teams (genart, etc).

**Comment by mskucherawy** [comment]
I think that's beyond what this document needs to deliver.  I think of this as being guidance to get people to the point of Publication Requested, and the review teams are usually called in during Last Calls.

I'm happy to cede to a different position if that's the consensus though.

**Comment by rjsparks** [comment]
Except there is the concept of early review...
I don't feel strongly.

**Comment by rjsparks** [comment]
Closing this. The pressure to use early reviews should probably be aimed at with someone in a position of stream authority rather than authors.
