### ISSUE TITLE
Too early dive into tools

### ISSUE THREAD

**Issue by LPardue** [ietf/id-guidelines#16]
In the introduction

> There are tools to help with the creation of Internet-Drafts. Rather than attempting to construct a plaintext Internet-Draft manually, it is highly recommended using a structured language for authoring, and a toolchain like xml2rfc or kramdown-rfc2629 to build a submission.

From how the intro progresses, that's a huge leap and presumes the reader has some knowledge of formats and tools. Suggest that a more accessible paragraph is introduced about input and output formats, with a nudge towards using structured inputs. That might borrow some text from other parts of the introduction.

**Comment by larseggert** [comment]
Would you mind proposing a PR along these lines?
