### ISSUE TITLE
The background section is not very helpful

### ISSUE THREAD

**Issue by LPardue** [ietf/id-guidelines#17]
What is supposed to be the purpose of the Background section? It seems to really be a detour into some content management details that are irrelevant for most authors. In my 5 years of writing I-Ds I've never known there was an "I-D repository", and I don't see much reason that it would have helped me,

Since this section doesn't establish any background to the concepts under discussion lower in the text. I suggest you rename this section and move it to a less prominent position in the document.

**Comment by larseggert** [comment]
Would you mind proposing a PR along these lines?
