### ISSUE TITLE
internet draft names too formalized

### ISSUE THREAD

**Issue by mcr** [ietf/id-guidelines#26]
The section on Internet-Draft Names reads like english version of ABNF.
Maybe move all the detailed rules to the end (and appendix, or another document).
New authors need to know:
  1. starts with draft
  2. then their lastname (avoiding "ietf", and some other reserved things)
  3. then the target WG
  4. then something unique that has some relationship to the title
 
but not too long.  The maximum length is not mentioned.

RFC7212 might be worth mentioning as well as RFC2026 when it comes to adoption process.

**Comment by larseggert** [comment]
Would you mind proposing a PR along these lines?
