### ISSUE TITLE
https://www.ietf.org/standards/ids/guidelines/ has additional material

### ISSUE THREAD

**Issue by larseggert** [ietf/id-guidelines#49]
Have we verified that all the material from https://www.ietf.org/standards/ids/guidelines/ is included in this re-write? Specifically, the boilerplate content in [Section 5](https://www.ietf.org/standards/ids/guidelines/#5) seems to be missing?

**Comment by larseggert** [comment]
@ghwood @JayDaley: I assume the content here would replace that web site eventually?

**Comment by JayDaley** [comment]
Yes though we need to decide if it replaces this page directly or goes onto an authors micro-site.
