### ISSUE TITLE
Increased use of group names anywhere in the SHORT-DOC-TITLE 

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf/id-guidelines#52]
> A popular convention is that an individual submission seeking adoption by a working group will **include the working group's acronym just after the second component.** For example, a person or group identified as "authors" seeking to get a document about "specific-subject" adopted by the "wgname" working group might choose the name **draft-authors-wgname**-specific-subject, and submit the file **draft-authors-wgname**-specific-subject-00.xml. 

This was also my understanding until about 24 hours ago, when I asked about what I was seeing for two of my drafts on [tools-discuss](https://mailarchive.ietf.org/arch/msg/tools-discuss/ObbkYk0LRYtHnA4jk78oKEaCfBI/) (the entire thread is probably relevant to this issue.

I was not aware that the current datatracker implementation allows group chairs to "tune" the matching rules for documents. Some chairs reported using matching rules that matched their group names anywhere in the SHORT-DOC-TITLEs, not just **just after the second component**, and there are likely other useful practices (as a hypothetical example, 6MAN might add an "All I-Ds with particular text/regular expression in the name" rule that matches "ICMPv6").

I don't know what to suggest for new text, but ISTM that the new I-D guidelines should at least say something about this. One possibility would be distinguishing between "targeted at an existing group, with the group name at the beginning of the SHORT-DOC-TITLE" and "potentially of interest to an existing group, with the group name anywhere in the SHORT-DOC-TITLE", which seemed to be behind the more permissive matching rule for QUIC?

And yes, text describing the actual practice should be discussed in the right place, before merging any PR that provides that text.

**Comment by larseggert** [comment]
I think the text as written is fine, because the convention really is that if you want to target a WG, name it in the second component. 

If a WG chooses to also track other drafts based on some form of name matching, that is IMO entirely orthogonal and should not impact how people name their drafts.

**Comment by SpencerDawkins** [comment]
@larseggert , thanks for the helpful reply. It clarified what I should have been asking about. 

I agree that the text as written defines the current convention (check). I wonder if we can do better than the current convention, but understand that I shouldn't be proposing text without getting feedback on a clear statement of purpose. 

My "hypothetical" example,

> (As a hypothetical example, 6MAN might add an "All I-Ds with particular text/regular expression in the name" rule that matches "ICMPv6")

was actually based on a private email exchange with Bob Hinden, who said that it's difficult for the 6MAN chairs to track "potentially of interest" I-Ds because (now quoting Bob),

> QUIC is both the name of the w.g. and of the protocol, so using “QUIC" can catch a lot of related drafts.
> 6MAN has a different issue, as we have IPv6, Neighbor Discovery (ND), ICMPv6, etc.   Harder to catch everything even if you are looking.

I picked the draft names that started this conversation, draft-dawkins-sdp-rtp-quic and draft-dawkins-sdp-rtp-quic-questions, because both were (literally) about IANA SDP registrations that would allow the use of RTP over QUIC. MMUSIC (the group) is responsible for SDP (the protocol), and AVTCORE (the group) is responsible for RTP (the protocol). ​I could have picked draft-dawkins-mmusic-sdp-rtp-quic, or draft-dawkins-avtcore-sdp-rtp-quic, and my draft would have automagically appeared for one of the two relevant groups, but it's not showing up as related for either of them now, and I don't think there's a way for me to know how to call attention to my drafts without asking the group chairs (and, I suspect, asking them to adjust their matching expressions). 

So what I'm wondering is, whether the right thing to do is to close this issue, and then ask in a reasonable place whether it's useful to think about draft file names as a way for draft submitters and group chairs to help each other call attention to the right drafts in the right place(s). I'm thinking on wgchairs.

**Comment by larseggert** [comment]
I am all for closing this issue :-)

I also think that we already encode way too much information into draft names, using a pretty arcane format, and encoding more information will be even more confusing, esp. to newcomers.
